GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Sixth blog",
    "author": "Me",
    "url": "http://www.mysixthblog.com",
    "likes": 66
}

###
DELETE http://localhost:3003/api/blogs/647d949493398478137d6b68

###
PUT http://localhost:3003/api/blogs/647d8c49a2590bd8d0bca8e3
Content-Type: application/json

{
     "title": "Updated blog",
    "author": "Update Me",
    "url": "http://www.myupdateblog.com",
    "likes": 22
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "rakshank",
    "name" : "Rakshan Kumar",
    "password": "myPassword"
}