GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Fourth blog",
    "author": "You",
    "url": "http://www.myfourthblog.com",
    "likes": 55
}