GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Sixth blog",
    "author": "Me",
    "url": "http://www.mysixthblog.com",
    "likes": 66
}